import type { SavingsScenario } from "./data.js";

export function getSavingsLabScenarios(locale: 'es' | 'en' = 'en'): SavingsScenario[] {
  const scenarios: SavingsScenario[] = [
    {
      id: 'daily-search',
      title: 'Daily Code Discovery',
      description: 'A developer doing 8 AI-assisted tasks per day in a medium TypeScript project. Each task starts with "where is X defined" or "who calls Y".',
      team: '1 dev · medium project · Sonnet',
      withoutLynx: { discoveryTokens: 18000, timeSeconds: 180, operations: 34, hallucinations: 2, reworkMinutes: 6, iterations: 2.5 },
      withLynx: { discoveryTokens: 2400, timeSeconds: 18, operations: 4, hallucinations: 0, reworkMinutes: 0, iterations: 1.0 },
      savings: {
        tokens: 15600,
        timeSeconds: 162,
        operations: 30,
        dollarsPerMonth: 47,
        hoursPerMonth: 1.8,
        mainWin: '15,600 tokens saved per day. 87% fewer tool calls. Zero hallucinated imports.',
      },
      dimensions: [
        { label: 'Search ops avoided', saving: '30 grep/glob → 3 search_graph' },
        { label: 'Wrong reads eliminated', saving: '~8 files not read (2 hallucinated symbols)' },
        { label: 'Iterations saved', saving: '2.5 rounds → 1 (1.5 rounds of grep→read→refine gone)' },
        { label: 'Context contamination', saving: '15K tokens freed for actual reasoning' },
      ],
    },
    {
      id: 'impact-analysis',
      title: 'Impact Analysis Before Refactor',
      description: 'A senior dev needs to rename a shared utility function. Without LYNX: blind grep, miss edge cases, break 3 callers. With LYNX: trace_path shows exact blast radius.',
      team: '1 senior dev · large project · Claude Opus',
      withoutLynx: { discoveryTokens: 35000, timeSeconds: 420, operations: 52, hallucinations: 3, reworkMinutes: 25, iterations: 3.5 },
      withLynx: { discoveryTokens: 1800, timeSeconds: 12, operations: 3, hallucinations: 0, reworkMinutes: 0, iterations: 1.0 },
      savings: {
        tokens: 33200,
        timeSeconds: 408,
        operations: 49,
        dollarsPerMonth: 186,
        hoursPerMonth: 4.2,
        mainWin: 'Prevents 3 regressions. trace_path shows all 146 callers before touching anything.',
      },
      dimensions: [
        { label: 'Regression prevention', saving: '3 broken callers caught before commit' },
        { label: 'Model tier downgrade', saving: 'Higher-cost model → lower-cost model with LYNX context' },
        { label: 'Rework avoided', saving: '25 min fixing broken callers → 0 min' },
        { label: 'Confidence', saving: 'trace_path gives exact call graph instead of guessing' },
      ],
    },
    {
      id: 'onboarding',
      title: 'New Developer Onboarding',
      description: 'A new hire joining a large monorepo. Without LYNX: 5 days reading code + asking seniors. With LYNX: pack_context + get_architecture gives the map in 10 minutes.',
      team: '1 new hire · large monorepo · first week',
      withoutLynx: { discoveryTokens: 450000, timeSeconds: 144000, operations: 400, hallucinations: 0, reworkMinutes: 0, iterations: 0 },
      withLynx: { discoveryTokens: 12000, timeSeconds: 600, operations: 8, hallucinations: 0, reworkMinutes: 0, iterations: 0 },
      savings: {
        tokens: 438000,
        timeSeconds: 143400,
        operations: 392,
        dollarsPerMonth: 0,
        hoursPerMonth: 0,
        mainWin: 'Onboarding drops from 5 days to 1 day. 32 hours of engineering time recovered per hire.',
      },
      dimensions: [
        { label: 'Time to first commit', saving: '5 days → 1 day (80% faster onboarding)' },
        { label: 'Senior interruptions', saving: '~15 "where is X" questions avoided' },
        { label: 'Mental model accuracy', saving: 'Graph-verified architecture vs word-of-mouth' },
        { label: 'Knowledge retention', saving: 'Graph stays when seniors leave' },
      ],
    },
    {
      id: 'multi-agent',
      title: 'Multi-Agent Parallel Work',
      description: '3 AI agents working in parallel on different parts of a feature. Without LYNX: each agent explores independently, duplicating work. With LYNX: all 3 query the same graph.',
      team: '3 AI agents · large project · Sonnet',
      withoutLynx: { discoveryTokens: 54000, timeSeconds: 540, operations: 102, hallucinations: 5, reworkMinutes: 12, iterations: 2.5 },
      withLynx: { discoveryTokens: 4800, timeSeconds: 24, operations: 9, hallucinations: 0, reworkMinutes: 0, iterations: 1.1 },
      savings: {
        tokens: 49200,
        timeSeconds: 516,
        operations: 93,
        dollarsPerMonth: 295,
        hoursPerMonth: 8.6,
        mainWin: '3x cost multiplier eliminated. Graph queried once, cached for all 3 agents.',
      },
      dimensions: [
        { label: 'Deduplicated exploration', saving: '3× grep overhead → 1× shared graph query' },
        { label: 'Consistent understanding', saving: 'All agents work from same code map' },
        { label: 'Parallel safety', saving: 'Each agent knows what others are touching' },
        { label: 'Model savings', saving: 'Reduced API cost per task through shared graph queries' },
      ],
    },
    {
      id: 'monthly-team',
      title: 'Team of 5, One Month',
      description: 'A 5-person team using AI assistants daily for a month on a large production project. This is the scenario that pays for LYNX.',
      team: '5 devs · large project · 20 working days',
      withoutLynx: { discoveryTokens: 900000, timeSeconds: 43200, operations: 3400, hallucinations: 45, reworkMinutes: 540, iterations: 2.5 },
      withLynx: { discoveryTokens: 126000, timeSeconds: 3600, operations: 240, hallucinations: 3, reworkMinutes: 18, iterations: 1.1 },
      savings: {
        tokens: 774000,
        timeSeconds: 39600,
        operations: 3160,
        dollarsPerMonth: 760,
        hoursPerMonth: 28.5,
        mainWin: '774K tokens saved. 39.6K search seconds eliminated. 3,160 search operations avoided.',
      },
      dimensions: [
        { label: 'API cost savings', saving: 'Reduced exploration tokens through graph-based discovery' },
        { label: 'Developer time', saving: '11 hours saved in search operations across the month' },
        { label: 'Errors prevented', saving: '42 hallucinated symbols/imports caught before commit' },
        { label: 'Knowledge base', saving: 'Graph serves as institutional memory for all 5 devs' },
        { label: 'Onboarding', saving: '1.5 new hires/month × 4 days saved each = 48h/year' },
        { label: 'Model tier flexibility', saving: 'Team can use lower-cost models with graph context' },
        { label: 'Context quality', saving: '~774K tokens/month freed for reasoning instead of searching' },
      ],
    },
  ];
  if (locale !== 'es') return scenarios;

  const copy: Record<string, string> = {
    'Daily Code Discovery': 'Descubrimiento diario de código',
    'A developer doing 8 AI-assisted tasks per day in a medium TypeScript project. Each task starts with "where is X defined" or "who calls Y".': 'Un desarrollador realiza 8 tareas diarias asistidas por IA en una base TypeScript mediana. Cada una empieza con «dónde se define X» o «quién llama a Y».',
    '1 dev · medium project · Sonnet': '1 desarrollador · código mediano · Sonnet',
    '15,600 tokens saved per day. 87% fewer tool calls. Zero hallucinated imports.': '15.600 tokens ahorrados al día. 87% menos llamadas a herramientas. Cero importaciones alucinadas.',
    'Search ops avoided': 'Operaciones de búsqueda evitadas', '30 grep/glob → 3 search_graph': '30 grep/glob → 3 search_graph',
    'Wrong reads eliminated': 'Lecturas erróneas eliminadas', '~8 files not read (2 hallucinated symbols)': '~8 archivos no leídos (2 símbolos alucinados)',
    'Iterations saved': 'Iteraciones ahorradas', '2.5 rounds → 1 (1.5 rounds of grep→read→refine gone)': '2,5 rondas → 1 (eliminadas 1,5 rondas de grep→leer→refinar)',
    'Context contamination': 'Contaminación de contexto', '15K tokens freed for actual reasoning': '15K tokens liberados para el razonamiento real',
    'Impact Analysis Before Refactor': 'Análisis de impacto antes de refactorizar',
    'A senior dev needs to rename a shared utility function. Without LYNX: blind grep, miss edge cases, break 3 callers. With LYNX: trace_path shows exact blast radius.': 'Un desarrollador sénior debe renombrar una utilidad compartida. Sin LYNX: búsquedas a ciegas, casos límite perdidos y 3 llamadores rotos. Con LYNX: trace_path muestra el impacto exacto.',
    '1 senior dev · large project · Claude Opus': '1 desarrollador sénior · código grande · Claude Opus',
    'Prevents 3 regressions. trace_path shows all 146 callers before touching anything.': 'Evita 3 regresiones. trace_path muestra los 146 llamadores antes de tocar nada.',
    'Regression prevention': 'Prevención de regresiones', '3 broken callers caught before commit': '3 llamadores rotos detectados antes del commit',
    'Model tier downgrade': 'Uso de un modelo más eficiente', 'Higher-cost model → lower-cost model with LYNX context': 'Modelo de mayor coste → modelo más eficiente con contexto de LYNX',
    'Rework avoided': 'Retrabajo evitado', '25 min fixing broken callers → 0 min': '25 min arreglando llamadores rotos → 0 min',
    'Confidence': 'Confianza', 'trace_path gives exact call graph instead of guessing': 'trace_path ofrece el grafo de llamadas exacto en lugar de adivinar',
    'New Developer Onboarding': 'Incorporación de un nuevo desarrollador',
    'A new hire joining a large monorepo. Without LYNX: 5 days reading code + asking seniors. With LYNX: pack_context + get_architecture gives the map in 10 minutes.': 'Una nueva incorporación entra en un monorepo grande. Sin LYNX: 5 días leyendo código y preguntando. Con LYNX: pack_context + get_architecture dan el mapa en 10 minutos.',
    '1 new hire · large monorepo · first week': '1 nueva incorporación · monorepo grande · primera semana',
    'Onboarding drops from 5 days to 1 day. 32 hours of engineering time recovered per hire.': 'La incorporación baja de 5 días a 1. Se recuperan 32 horas de ingeniería por persona.',
    'Time to first commit': 'Tiempo hasta el primer commit', '5 days → 1 day (80% faster onboarding)': '5 días → 1 día (incorporación un 80% más rápida)',
    'Senior interruptions': 'Interrupciones a perfiles sénior', '~15 "where is X" questions avoided': '~15 preguntas de «dónde está X» evitadas',
    'Mental model accuracy': 'Precisión del modelo mental', 'Graph-verified architecture vs word-of-mouth': 'Arquitectura verificada por el grafo frente a conocimiento informal',
    'Knowledge retention': 'Retención de conocimiento', 'Graph stays when seniors leave': 'El grafo permanece cuando se van perfiles sénior',
    'Multi-Agent Parallel Work': 'Trabajo paralelo multiagente',
    '3 AI agents working in parallel on different parts of a feature. Without LYNX: each agent explores independently, duplicating work. With LYNX: all 3 query the same graph.': '3 agentes de IA trabajan en paralelo en partes distintas de una funcionalidad. Sin LYNX: cada agente explora por su cuenta y duplica trabajo. Con LYNX: los 3 consultan el mismo grafo.',
    '3 AI agents · large project · Sonnet': '3 agentes de IA · código grande · Sonnet',
    '3x cost multiplier eliminated. Graph queried once, cached for all 3 agents.': 'Eliminado el multiplicador de coste ×3. El grafo se consulta una vez y se reutiliza para los 3 agentes.',
    'Deduplicated exploration': 'Exploración sin duplicados', '3× grep overhead → 1× shared graph query': 'sobrecoste de grep ×3 → una consulta compartida al grafo',
    'Consistent understanding': 'Comprensión coherente', 'All agents work from same code map': 'Todos los agentes trabajan desde el mismo mapa de código',
    'Parallel safety': 'Seguridad en paralelo', 'Each agent knows what others are touching': 'Cada agente sabe qué están tocando los demás',
    'Model savings': 'Ahorro de modelo', 'Reduced API cost per task through shared graph queries': 'Coste de API reducido por tarea gracias a consultas compartidas al grafo',
    'Team of 5, One Month': 'Equipo de 5, un mes',
    'A 5-person team using AI assistants daily for a month on a large production project. This is the scenario that pays for LYNX.': 'Un equipo de 5 personas usa asistentes de IA a diario durante un mes en una base de producción grande. Este escenario amortiza LYNX.',
    '5 devs · large project · 20 working days': '5 desarrolladores · código grande · 20 días laborables',
    '$760/month net savings. 28.5 dev hours recovered. 42 hallucinations prevented. ROI: 7.6x.': '774K tokens ahorrados. 39,6K segundos de búsqueda eliminados. 3.160 operaciones evitadas.',
    '774K tokens saved. 39.6K search seconds eliminated. 3,160 search operations avoided.': '774K tokens ahorrados. 39,6K segundos de búsqueda eliminados. 3.160 operaciones evitadas.',
    'API cost savings': 'Ahorro de coste de API', 'Reduced exploration tokens through graph-based discovery': 'Tokens de exploración reducidos gracias al descubrimiento basado en el grafo',
    'Developer time': 'Tiempo de desarrollo', '11 hours saved in search operations across the month': '11 horas ahorradas en operaciones de búsqueda durante el mes',
    'Errors prevented': 'Errores evitados', '42 hallucinated symbols/imports caught before commit': '42 símbolos o importaciones alucinados detectados antes del commit',
    'Knowledge base': 'Base de conocimiento', 'Graph serves as institutional memory for all 5 devs': 'El grafo sirve de memoria institucional para los 5 desarrolladores',
    'Onboarding': 'Incorporación', '1.5 new hires/month × 4 days saved each = 48h/year': '1,5 nuevas incorporaciones/mes × 4 días ahorrados = 48 h/año',
    'Model tier flexibility': 'Flexibilidad de modelo', 'Team can use lower-cost models with graph context': 'El equipo puede usar modelos más económicos con contexto del grafo',
    'Context quality': 'Calidad del contexto', '~774K tokens/month freed for reasoning instead of searching': '~774K tokens/mes liberados para razonar en vez de buscar',
  };
  return scenarios.map((scenario) => ({
    ...scenario,
    title: copy[scenario.title] || scenario.title,
    description: copy[scenario.description] || scenario.description,
    team: copy[scenario.team] || scenario.team,
    savings: { ...scenario.savings, mainWin: copy[scenario.savings.mainWin] || scenario.savings.mainWin },
    dimensions: scenario.dimensions.map((dimension) => ({ label: copy[dimension.label] || dimension.label, saving: copy[dimension.saving] || dimension.saving })),
  }));
}
