#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { int id; char *project; char *relPath; char *absPath; } Task;
typedef struct { char *name; char *kind; int line; int end_line; int is_exported; } Def;
typedef struct { Def *items; int len, cap; } Defs;
typedef struct { char *data; size_t len, cap; } Buf;

static void binit(Buf *b){ b->cap=1<<20; b->len=0; b->data=(char*)malloc(b->cap); b->data[0]=0; }
static void bgrow(Buf *b,size_t n){ if(b->len+n+1>b->cap){ while(b->len+n+1>b->cap)b->cap*=2; b->data=(char*)realloc(b->data,b->cap);} }
static void bputn(Buf*b,const char*s,size_t n){ bgrow(b,n); memcpy(b->data+b->len,s,n); b->len+=n; b->data[b->len]=0; }
static void bputs(Buf*b,const char*s){ bputn(b,s,strlen(s)); }
static void bch(Buf*b,char c){ bgrow(b,1); b->data[b->len++]=c; b->data[b->len]=0; }
static void bjson(Buf*b,const char*s){ bch(b,'"'); for(;*s;s++){ unsigned char c=*s; if(c=='"'||c=='\\'){ bch(b,'\\'); bch(b,c);} else if(c=='\n') bputs(b,"\\n"); else if(c=='\r') bputs(b,"\\r"); else if(c=='\t') bputs(b,"\\t"); else if(c<32) bch(b,' '); else bch(b,c);} bch(b,'"'); }
static char* slurp(const char*path,size_t*out){ FILE*f=fopen(path,"rb"); if(!f)return NULL; fseek(f,0,SEEK_END); long n=ftell(f); fseek(f,0,SEEK_SET); if(n<0){fclose(f);return NULL;} char*p=(char*)malloc((size_t)n+1); size_t r=fread(p,1,(size_t)n,f); fclose(f); p[r]=0; *out=r; return p; }
static char* slurp_stdin(size_t*out){ size_t cap=1<<20,len=0; char*p=(char*)malloc(cap+1); for(;;){ if(len+65536>cap){cap*=2;p=(char*)realloc(p,cap+1);} size_t r=fread(p+len,1,65536,stdin); len+=r; if(r<65536){ if(feof(stdin))break; if(ferror(stdin)){free(p);return NULL;} } } p[len]=0; *out=len; return p; }
static uint64_t fnv(const char*p,size_t n){ uint64_t h=1469598103934665603ULL; for(size_t i=0;i<n;i++){ h^=(unsigned char)p[i]; h*=1099511628211ULL;} return h; }
static int isid0(char c){ return isalpha((unsigned char)c)||c=='_'||c=='$'; }
static int isid(char c){ return isalnum((unsigned char)c)||c=='_'||c=='$'; }
static int line_of(const char*s,size_t pos){ int line=1; for(size_t i=0;i<pos;i++) if(s[i]=='\n') line++; return line; }
static int count_lines(const char*s,size_t n){ int line=1; for(size_t i=0;i<n;i++) if(s[i]=='\n') line++; return line; }
static char* dup_range(const char*s,size_t a,size_t b){ char*p=(char*)malloc(b-a+1); memcpy(p,s+a,b-a); p[b-a]=0; return p; }
static const char* base(const char*p){ const char*s=strrchr(p,'/'); return s?s+1:p; }
static char* module_qn(const char*path){ char*p=strdup(path); char*dot=strrchr(p,'.'); if(dot)*dot=0; char*out=(char*)malloc(strlen(p)+1); size_t j=0; char*start=p; if(strncmp(start,"src/",4)==0) start+=4; for(size_t i=0;start[i];i++) out[j++]= start[i]=='/'?'.':start[i]; out[j]=0; size_t l=strlen(out); if(l>=6 && strcmp(out+l-6,".index")==0) out[l-6]=0; free(p); return out; }
static void skip_ws(const char**p){ while(**p && isspace((unsigned char)**p))(*p)++; }
static char* parse_str(const char**p){ skip_ws(p); if(**p!='"') return strdup(""); (*p)++; Buf b; binit(&b); while(**p && **p!='"'){ if(**p=='\\' && (*p)[1]) (*p)++; bch(&b,**p); (*p)++; } if(**p=='"')(*p)++; return b.data; }
static int parse_int(const char**p){ skip_ws(p); int v=0; while(isdigit((unsigned char)**p)){ v=v*10+(**p-'0'); (*p)++; } return v; }
static char* find_prop_str(const char*obj,const char*key){ char pat[64]; snprintf(pat,sizeof(pat),"\"%s\"",key); const char*p=strstr(obj,pat); if(!p)return strdup(""); p=strchr(p,':'); if(!p)return strdup(""); p++; return parse_str(&p); }
static int find_prop_int(const char*obj,const char*key){ char pat[64]; snprintf(pat,sizeof(pat),"\"%s\"",key); const char*p=strstr(obj,pat); if(!p)return 0; p=strchr(p,':'); if(!p)return 0; p++; return parse_int(&p); }
static Task* parse_tasks(const char*json,int*count){ int cap=128,n=0; Task*t=(Task*)calloc(cap,sizeof(Task)); const char*p=json; while((p=strchr(p,'{'))){ const char*e=strchr(p,'}'); if(!e)break; char*obj=dup_range(p,0,(size_t)(e-p+1)); if(n==cap){cap*=2;t=(Task*)realloc(t,cap*sizeof(Task));} t[n].id=find_prop_int(obj,"id"); t[n].project=find_prop_str(obj,"project"); t[n].relPath=find_prop_str(obj,"relPath"); t[n].absPath=find_prop_str(obj,"absPath"); n++; free(obj); p=e+1; } *count=n; return t; }
static void node(Buf*b,const char*project,const char*kind,const char*name,const char*qn,const char*file,int startLine,int endLine,int isExported,const char*extra){ bputs(b,"{\"project\":"); bjson(b,project); bputs(b,",\"kind\":"); bjson(b,kind); bputs(b,",\"name\":"); bjson(b,name); bputs(b,",\"qualifiedName\":"); bjson(b,qn); bputs(b,",\"filePath\":"); bjson(b,file); char tmp[256]; snprintf(tmp,sizeof(tmp),",\"startLine\":%d,\"endLine\":%d,\"isExported\":%s,\"isTest\":false,\"isEntryPoint\":false",startLine,endLine,isExported?"true":"false"); bputs(b,tmp); if(extra)bputs(b,extra); bch(b,'}'); }
static void emit_name_node(Buf*b,int*first,const char*project,const char*mod,const char*kind,const char*name,const char*file,int startLine,int endLine,int isExported){ if(!name||!name[0]||name[0]=='_')return; if(!*first)bch(b,','); *first=0; char qn[4096]; snprintf(qn,sizeof(qn),"%s.%s",mod,name); int lc=endLine-startLine+1; if(lc<1)lc=1; char lcStr[64]; snprintf(lcStr,sizeof(lcStr),",\"lineCount\":%d",lc); char extraBuf[256]=""; if(strcmp(kind,"Function")==0) snprintf(extraBuf,sizeof(extraBuf),",\"signature\":null,\"paramNames\":[],\"cyclomaticComplexity\":0%s",lcStr); else if(strcmp(kind,"Class")==0) snprintf(extraBuf,sizeof(extraBuf),",\"baseClasses\":[],\"cyclomaticComplexity\":0%s",lcStr); else if(strcmp(kind,"Interface")==0) snprintf(extraBuf,sizeof(extraBuf),",\"baseInterfaces\":[]"); else if(strcmp(kind,"Enum")==0) snprintf(extraBuf,sizeof(extraBuf),",\"members\":[]"); else if(strcmp(kind,"Variable")==0) snprintf(extraBuf,sizeof(extraBuf),",\"typeAnnotation\":null"); node(b,project,kind,name,qn,file,startLine,endLine,isExported,extraBuf); }
static int kw_at(const char*s,size_t i,size_t n,const char*kw){ size_t k=strlen(kw); return i+k<n && strncmp(s+i,kw,k)==0 && (i==0||!isid(s[i-1])) && !isid(s[i+k]); }
static size_t skip_space(const char*s,size_t i,size_t n){ while(i<n && isspace((unsigned char)s[i]))i++; return i; }
static char* read_ident(const char*s,size_t*i,size_t n){ size_t a=*i; if(a>=n||!isid0(s[a]))return NULL; (*i)++; while(*i<n&&isid(s[*i]))(*i)++; return dup_range(s,a,*i); }
static int skip_usage_name(const char*name){ const char*kw[]={"abstract","any","as","async","await","boolean","break","case","catch","class","className","const","constructor","continue","debugger","declare","default","delete","do","else","enum","export","extends","false","finally","for","from","function","if","implements","import","in","infer","instanceof","interface","is","keyof","let","module","namespace","never","new","not","null","number","object","of","package","private","protected","public","readonly","return","satisfies","static","string","super","switch","symbol","this","throw","true","try","type","typeof","undefined","unknown","var","void","while","with","yield",NULL}; for(int i=0;kw[i];i++) if(strcmp(name,kw[i])==0) return 1; return 0; }
static int skip_jsx_attr_name(const char*name,int isWrite){ if(!isWrite)return 0; const char*attrs[]={"alt","aria","ariaLabel","children","className","colSpan","disabled","height","href","htmlFor","id","key","placeholder","rel","role","rowSpan","src","style","target","title","type","value","width",NULL}; for(int i=0;attrs[i];i++) if(strcmp(name,attrs[i])==0) return 1; return 0; }
static void defs_push(Defs*d,char*name,char*kind,int line){ if(d->len==d->cap){d->cap=d->cap?d->cap*2:64; d->items=(Def*)realloc(d->items,d->cap*sizeof(Def));} d->items[d->len].name=strdup(name); d->items[d->len].kind=kind; d->items[d->len].line=line; d->items[d->len].end_line=line; d->len++; }
static void scope_qn(char*out,size_t cap,const char*mod,Defs*d,int line){ const char*name=NULL; int best=0; for(int i=0;i<d->len;i++){ if(strcmp(d->items[i].kind,"Function")!=0)continue; if(d->items[i].line<=line && line<=d->items[i].end_line && d->items[i].line>=best){best=d->items[i].line; name=d->items[i].name;} } if(name) snprintf(out,cap,"%s.%s",mod,name); else snprintf(out,cap,"%s._global",mod); }
static int find_closing_brace(const char*s,size_t n,size_t start){ int depth=0; for(size_t i=start;i<n;i++){ if(s[i]=='{') depth++; else if(s[i]=='}'){ depth--; if(depth==0) return i; } } return -1; }
static int is_exported(const char*s,size_t i){ while(i>0&&isspace((unsigned char)s[i-1]))i--; if(i>=7&&strncmp(s+i-7,"default",7)==0&&(i==7||!isid(s[i-8]))){i-=7;while(i>0&&isspace((unsigned char)s[i-1]))i--;} if(i>=6&&strncmp(s+i-6,"export",6)==0&&(i==6||!isid(s[i-7])))return 1;return 0; }

static void extract_defs(Buf*b,int*first,const char*s,size_t n,const char*project,const char*mod,const char*file,Defs*defs){ int line=1; int in_line_comment=0,in_block_comment=0,in_string=0,in_template=0; char string_char=0; for(size_t i=0;i<n;i++){ char c=s[i]; char pc=i>0?s[i-1]:0; if(c=='\n'){line++;in_line_comment=0;continue;} if(!in_string&&!in_template&&!in_line_comment&&!in_block_comment){ if(c=='/'&&i+1<n){ if(s[i+1]=='/')in_line_comment=1; else if(s[i+1]=='*')in_block_comment=1; } else if(c=='"'||c=='\''){in_string=1;string_char=c;} else if(c=='`')in_template=1; } else if(in_block_comment&&c=='*'&&i+1<n&&s[i+1]=='/'){in_block_comment=0;i++;continue;} else if(in_string&&c==string_char&&pc!='\\')in_string=0; else if(in_template&&c=='`'&&pc!='\\')in_template=0; if(in_line_comment||in_block_comment||in_string||in_template)continue; const char*kind=NULL; size_t j=i; if(kw_at(s,i,n,"function")){kind="Function";j=i+8;} else if(kw_at(s,i,n,"class")){kind="Class";j=i+5;} else if(kw_at(s,i,n,"interface")){kind="Interface";j=i+9;} else if(kw_at(s,i,n,"type")){kind="Type";j=i+4;} else if(kw_at(s,i,n,"enum")){kind="Enum";j=i+4;} else if(kw_at(s,i,n,"const")||kw_at(s,i,n,"let")||kw_at(s,i,n,"var")){kind="Variable";j=i+(s[i]=='c'?5:3);} else continue; j=skip_space(s,j,n); char*name=read_ident(s,&j,n); if(name){ defs_push(defs,name,(char*)kind,line); defs->items[defs->len-1].is_exported=is_exported(s,i); free(name);} } int total=count_lines(s,n); for(int k=0;k<defs->len;k++){ int end=0; if(strcmp(defs->items[k].kind,"Function")==0||strcmp(defs->items[k].kind,"Class")==0){ const char*lineStart=s; int ln=1; for(;ln<defs->items[k].line;ln++){ lineStart=strchr(lineStart,'\n'); if(!lineStart){lineStart=s+n;break;} lineStart++; } const char*brace=strchr(lineStart,'{'); if(brace&&brace<s+n){ size_t idx=brace-s; int cpos=find_closing_brace(s,n,idx); if(cpos>=0) end=line_of(s,cpos); } if(end<defs->items[k].line) end=defs->items[k].line; } else { end=(k+1<defs->len)?defs->items[k+1].line-1:total; if(end<defs->items[k].line)end=defs->items[k].line; } defs->items[k].end_line=end; emit_name_node(b,first,project,mod,defs->items[k].kind,defs->items[k].name,file,defs->items[k].line,end,defs->items[k].is_exported); } }
static void emit_import(Buf*b,int*first,const char*name,const char*mod,int line){ if(!name||!name[0]||!mod||!mod[0])return; if(!*first)bch(b,','); *first=0; bputs(b,"{\"localName\":"); bjson(b,name); bputs(b,",\"modulePath\":"); bjson(b,mod); char tmp[64]; snprintf(tmp,sizeof(tmp),",\"startLine\":%d}",line); bputs(b,tmp); }
static void extract_imports(Buf*b,const char*s,size_t n){ int first=1; for(size_t i=0;i+6<n;i++){ if(!kw_at(s,i,n,"import"))continue; int line=line_of(s,i); size_t semi=i; while(semi<n&&s[semi]!='\n'&&s[semi]!=';')semi++; size_t q=i; while(q<semi&&s[q]!='\''&&s[q]!='\"')q++; if(q>=semi)continue; char quote=s[q++]; size_t a=q; while(q<semi&&s[q]!=quote)q++; if(q>=semi)continue; char*mod=dup_range(s,a,q); int emitted=0; size_t from=i; while(from+4<semi&&strncmp(s+from,"from",4)!=0)from++; size_t specEnd=from<semi?from:i; for(size_t p=i;p<specEnd;p++){ if(s[p]=='{'){ p++; while(p<specEnd&&s[p]!='}'){ while(p<specEnd&&(isspace((unsigned char)s[p])||s[p]==','))p++; size_t x=p; char*name=read_ident(s,&x,specEnd); if(name){ p=x; while(p<specEnd&&isspace((unsigned char)s[p]))p++; if(p+2<specEnd&&s[p]=='a'&&s[p+1]=='s'&&!isid(s[p+2])){ p+=2; p=skip_space(s,p,specEnd); x=p; char*alias=read_ident(s,&x,specEnd); if(alias){ emit_import(b,&first,alias,mod,line); emitted=1; free(alias);} } else { emit_import(b,&first,name,mod,line); emitted=1; } free(name); } else p++; } } else if(s[p]=='*'){ size_t x=p+1; while(x<specEnd&&isspace((unsigned char)s[x]))x++; if(x+2<specEnd&&s[x]=='a'&&s[x+1]=='s'){ x+=2; x=skip_space(s,x,specEnd); char*alias=read_ident(s,&x,specEnd); if(alias){ emit_import(b,&first,alias,mod,line); emitted=1; free(alias);} } } }
 if(!emitted){ size_t p=i+6; p=skip_space(s,p,specEnd); if(p<specEnd&&strncmp(s+p,"type",4)==0&&!isid(s[p+4]))p=skip_space(s,p+4,specEnd); char*def=read_ident(s,&p,specEnd); if(def){ emit_import(b,&first,def,mod,line); free(def); emitted=1; } }
 if(!emitted){ const char*slash=strrchr(mod,'/'); emit_import(b,&first,slash?slash+1:mod,mod,line); } free(mod); }}
static void extract_calls(Buf*b,const char*s,size_t n,const char*mod,Defs*defs){ int first=1,count=0,line=1; int in_line_comment=0,in_block_comment=0,in_string=0,in_template=0; char string_char=0; for(size_t i=0;i<n&&count<400;i++){ char c=s[i]; char pc=i>0?s[i-1]:0; if(c=='\n'){line++;in_line_comment=0;continue;} if(!in_string&&!in_template&&!in_line_comment&&!in_block_comment){ if(c=='/'&&i+1<n){ if(s[i+1]=='/')in_line_comment=1; else if(s[i+1]=='*')in_block_comment=1; } else if(c=='"'||c=='\''){in_string=1;string_char=c;} else if(c=='`')in_template=1; } else if(in_block_comment&&c=='*'&&i+1<n&&s[i+1]=='/'){in_block_comment=0;i++;continue;} else if(in_string&&c==string_char&&pc!='\\')in_string=0; else if(in_template&&c=='`'&&pc!='\\')in_template=0; if(in_line_comment||in_block_comment||in_string||in_template)continue; if(!isid0(s[i]))continue; size_t j=i; char*name=read_ident(s,&j,n); size_t k=skip_space(s,j,n); if(k<n&&s[k]=='(' && strcmp(name,"if")&&strcmp(name,"for")&&strcmp(name,"while")&&strcmp(name,"switch")&&strcmp(name,"catch")&&strcmp(name,"function")){ int isDecl=0; for(int d=0;d<defs->len;d++){ if(strcmp(defs->items[d].kind,"Function")==0&&defs->items[d].line==line&&strcmp(defs->items[d].name,name)==0){isDecl=1;break;} } if(!isDecl){ if(!first)bch(b,','); first=0; bputs(b,"{\"calleeName\":"); bjson(b,name); bputs(b,",\"enclosingFuncQn\":"); char qn[4096]; scope_qn(qn,sizeof(qn),mod,defs,line); bjson(b,qn); char tmp[80]; snprintf(tmp,sizeof(tmp),",\"args\":[],\"startLine\":%d}",line); bputs(b,tmp); count++; }} free(name); i=j; }}
static void extract_usages(Buf*b,const char*s,size_t n,const char*mod,Defs*defs){ int first=1,count=0,line=1; char seen[240][80]; int sn=0; int in_line_comment=0,in_block_comment=0,in_string=0,in_template=0; char string_char=0; for(size_t i=0;i<n&&count<240;i++){ char c=s[i]; char pc=i>0?s[i-1]:0; if(c=='\n'){line++;in_line_comment=0;continue;} if(!in_string&&!in_template&&!in_line_comment&&!in_block_comment){ if(c=='/'&&i+1<n){ if(s[i+1]=='/')in_line_comment=1; else if(s[i+1]=='*')in_block_comment=1; } else if(c=='"'||c=='\''){in_string=1;string_char=c;} else if(c=='`')in_template=1; } else if(in_block_comment&&c=='*'&&i+1<n&&s[i+1]=='/'){in_block_comment=0;i++;continue;} else if(in_string&&c==string_char&&pc!='\\')in_string=0; else if(in_template&&c=='`'&&pc!='\\')in_template=0; if(in_line_comment||in_block_comment||in_string||in_template)continue; if(!isid0(s[i]))continue; size_t j=i; char*name=read_ident(s,&j,n); if(strlen(name)>=3&&!skip_usage_name(name)){ size_t rhs=skip_space(s,j,n); int isWrite=(rhs<n&&s[rhs]=='='&&(rhs+1>=n||s[rhs+1]!='=')&&(rhs+1>=n||s[rhs+1]!='>')); if(!skip_jsx_attr_name(name,isWrite)){ int dup=0; for(int x=0;x<sn;x++) if(strcmp(seen[x],name)==0){dup=1;break;} if(!dup||isWrite){ if(!dup&&sn<240){ strncpy(seen[sn],name,79); seen[sn][79]=0; sn++; } if(!first)bch(b,','); first=0; bputs(b,"{\"refName\":"); bjson(b,name); bputs(b,",\"enclosingFuncQn\":"); char qn[4096]; scope_qn(qn,sizeof(qn),mod,defs,line); bjson(b,qn); char tmp[80]; snprintf(tmp,sizeof(tmp),",\"startLine\":%d,\"isWrite\":%s}",line,isWrite?"true":"false"); bputs(b,tmp); count++; }}} free(name); i=j; }}
static void extract_throws(Buf*b,const char*s,size_t n,const char*mod,Defs*defs){ int first=1,count=0,line=1; int in_line_comment=0,in_block_comment=0,in_string=0,in_template=0; char string_char=0; for(size_t i=0;i+4<n&&count<50;i++){ char c=s[i]; char pc=i>0?s[i-1]:0; if(c=='\n'){line++;in_line_comment=0;continue;} if(!in_string&&!in_template&&!in_line_comment&&!in_block_comment){ if(c=='/'&&i+1<n){ if(s[i+1]=='/')in_line_comment=1; else if(s[i+1]=='*')in_block_comment=1; } else if(c=='"'||c=='\''){in_string=1;string_char=c;} else if(c=='`')in_template=1; } else if(in_block_comment&&c=='*'&&i+1<n&&s[i+1]=='/'){in_block_comment=0;i++;continue;} else if(in_string&&c==string_char&&pc!='\\')in_string=0; else if(in_template&&c=='`'&&pc!='\\')in_template=0; if(in_line_comment||in_block_comment||in_string||in_template)continue; if(kw_at(s,i,n,"throw")){ size_t j=i+5; j=skip_space(s,j,n); if(j+3<n&&kw_at(s,j,n,"new")){j+=3;j=skip_space(s,j,n);} char*exc=read_ident(s,&j,n); if(exc&&strcmp(exc,"new")){ if(!first)bch(b,','); first=0; bputs(b,"{\"exceptionName\":"); bjson(b,exc); bputs(b,",\"enclosingFuncQn\":"); char qn[4096]; scope_qn(qn,sizeof(qn),mod,defs,line); bjson(b,qn); char tmp[80]; snprintf(tmp,sizeof(tmp),",\"startLine\":%d}",line); bputs(b,tmp); count++; free(exc); } i=j; } }}
static void emit_task(Buf*out,Task*t,int comma){ size_t n=0; char*s=slurp(t->absPath,&n); if(comma)bch(out,','); if(!s){ bputs(out,"{\"id\":"); char tmp[64]; snprintf(tmp,sizeof(tmp),"%d",t->id); bputs(out,tmp); bputs(out,",\"file\":{},\"sha256\":\"\",\"result\":{\"nodes\":[],\"calls\":[],\"imports\":[],\"usages\":[],\"channels\":[],\"throws\":[],\"decorators\":[],\"hasError\":true,\"errorMsg\":\"read failed\",\"isTestFile\":false,\"language\":\"unknown\"}}"); return;} char*mod=module_qn(t->relPath); int lines=count_lines(s,n); uint64_t h=fnv(s,n); char hash[32]; snprintf(hash,sizeof(hash),"%016llx",(unsigned long long)h); char tmp[512]; snprintf(tmp,sizeof(tmp),"{\"id\":%d,\"file\":{},\"sha256\":\"%s\",\"result\":{\"nodes\":[",t->id,hash); bputs(out,tmp); int first=1; char fileqn[4096],modqn[4096],extra[128]; Defs defs={0}; snprintf(fileqn,sizeof(fileqn),"%s.file.%s",t->project,mod); snprintf(extra,sizeof(extra),",\"extension\":\".%s\",\"lastModified\":0,\"changeCount\":0",strrchr(t->relPath,'.')?strrchr(t->relPath,'.')+1:""); node(out,t->project,"File",base(t->relPath),fileqn,t->relPath,1,1,0,extra); first=0; bch(out,','); snprintf(modqn,sizeof(modqn),"%s.module.%s",t->project,mod); snprintf(extra,sizeof(extra),",\"lineCount\":%d",lines); node(out,t->project,"Module",base(mod),modqn,t->relPath,1,1,0,extra); extract_defs(out,&first,s,n,t->project,mod,t->relPath,&defs); bputs(out,"],\"calls\":["); extract_calls(out,s,n,mod,&defs); bputs(out,"],\"imports\":["); extract_imports(out,s,n); bputs(out,"],\"usages\":["); extract_usages(out,s,n,mod,&defs); bputs(out,"],\"channels\":[],\"throws\":["); extract_throws(out,s,n,mod,&defs); bputs(out,"],\"decorators\":[],\"hasError\":false,\"errorMsg\":null,\"isTestFile\":false,\"language\":\"typescript\"}}"); free(mod); free(s); }
int main(){ size_t n=0; char*json=slurp_stdin(&n); if(!json)return 1; int count=0; Task*t=parse_tasks(json,&count); Buf out; binit(&out); bch(&out,'['); for(int i=0;i<count;i++) emit_task(&out,&t[i],i>0); bch(&out,']'); fwrite(out.data,1,out.len,stdout); return 0; }
