#!/usr/bin/env bash
# ci-assess.sh — Run LYNX assess_impact in CI and post results as a PR comment.
#
# Usage:
#   bash scripts/ci-assess.sh [project-name] [base-branch]
#
# The GH_TOKEN env var must be set for PR commenting (GitHub Actions provides
# this automatically. Locally, you can use `gh auth token`).

set -euo pipefail

PROJECT="${1:-LYNX}"
BASE="${2:-main}"

echo "=== LYNX CI Impact Assessment ==="
echo "Project: $PROJECT  Base: $BASE"
echo ""

# ── Step 1: index ────────────────────────────────────────────
echo "--- Indexing ---"
node dist/cli.js index . --name "$PROJECT" --mode fast --incremental || true
echo ""

# ── Step 2: assess ───────────────────────────────────────────
echo "--- Assess ---"
node scripts/run-assess.js --project "$PROJECT" --base-branch "$BASE" --json > /tmp/lynx-impact.json 2>/dev/null || {
  echo '{"summary":"assess_impact failed — likely no DB or no git diff"}'
}

# ── Step 3: format PR comment ─────────────────────────────────
SUMMARY=$(node -e "
  const d = require('/tmp/lynx-impact.json');
  console.log(d.summary || 'No summary available');
")

DEPENDENTS=$(node -e "
  const d = require('/tmp/lynx-impact.json');
  const dd = d.direct_dependent_files || [];
  const ad = d.async_dependent_files || [];
  const inv = d.sibling_invariants_broken || [];
  const arch = d.architecture_rules_broken || [];
  console.log('| Dimension | Result |');
  console.log('|-----------|--------|');
  console.log('| Blast Radius (CALLS) | ' + (dd.length > 0 ? dd.slice(0,5).map(f=>'\`'+f+'\`').join(', ') : 'none') + ' |');
  console.log('| Event Bridge (EMITS/LISTENS) | ' + (ad.length > 0 ? ad.slice(0,5).map(f=>'\`'+f+'\`').join(', ') : 'none') + ' |');
  console.log('| Sibling Invariants | ' + (inv.length > 0 ? inv.length + ' violation(s)' : 'none') + ' |');
  console.log('| Architecture Rules | ' + (arch.length > 0 ? arch.length + ' violation(s)' : 'none') + ' |');
")

FINDINGS=$(node -e "
  const d = require('/tmp/lynx-impact.json');
  const findings = d.findings || [];
  const total = d.total_findings || 0;
  const cats = d.findings_by_category || {};
  console.log('**Findings (' + total + ' total, ' + findings.length + ' shown):**');
  console.log('');
  for (const [cat, count] of Object.entries(cats)) {
    console.log('- ' + cat.replace(/_/g, ' ') + ': ' + count);
  }
  console.log('');
  if (findings.length > 0) {
    console.log('| Confidence | File | Detail |');
    console.log('|------------|------|--------|');
    for (const f of findings.slice(0, 10)) {
      const icon = f.overall_confidence === 'high' ? '!' : f.overall_confidence === 'medium' ? '~' : '.';
      console.log('| ' + icon + ' ' + f.overall_confidence + ' | \`' + (f.file || '') + '\` | ' + (f.detail || '').slice(0, 120) + ' |');
    }
  }
")

COMMENT="## LYNX Impact Assessment

${SUMMARY}

### Trinity of Validation

${DEPENDENTS}

${FINDINGS}

---
*Generated by LYNX assess_impact in CI. [Full JSON](https://github.com/${GITHUB_REPOSITORY:-cesarmesaspain/LYNX}/actions/runs/${GITHUB_RUN_ID:-?}).*"

echo "$COMMENT"
echo ""

# ── Step 4: post comment ──────────────────────────────────────
if [[ -n "${GITHUB_TOKEN:-}" || -n "${GH_TOKEN:-}" ]]; then
  if command -v gh &> /dev/null; then
    echo "$COMMENT" | gh pr comment "${GITHUB_REF_NAME:-}" --body-file - || true
    echo "PR comment posted."
  fi
else
  echo "No GH_TOKEN — skipping PR comment."
fi
